version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    networks:
      - default
      - fastapi-network
    volumes:
      - ./conf/postgresql.conf:/etc/postgresql/
      - ./dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER : ${POSTGRES_USER}
      POSTGRES_PASSWORD : ${POSTGRES_PASSWORD}
      POSTGRES_DB : ${POSTGRES_DB}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      POSTGRESQL_DIR : "./dbdata"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  fastapi:
    build:
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - default
      - fastapi-network
networks:
  fastapi-network:
    driver: bridge
